api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    path('v2/list/grantgoal/', views.GrantGoalListAPIView.as_view(), name="api_list_grantgoal"),
    path('v2/detail/grantgoal/<int:pk>/', views.GrantGoalDetailAPIView.as_view(), name="api_detail_grantgoal"),
    path('v2/create/grantgoal/', views.GrantGoalCreateAPIView.as_view(), name="api_create_grantgoal"),

    ### URL'S CLIENT ####

    path('client/list/grantgoal/', views.ListGrantGoalClient.as_view(), name="client_list"),
    path('client/create/grantgoal/', views.CreateGrantGoalClient.as_view(), name="api_create_client")
]

dplaest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
]

home/urls.py
from django.urls import path




from home import views


app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logoutView, name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('detail/profile/<int:pk>/', views.ProfileView.as_view(), name="profile_view"),
    path('udpate/profile/<int:pk>/', views.UpdateProfile.as_view(), name="update_profile"),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <!-- NAV BAR -->
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">Navbar</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Dropdown
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="#">Action</a></li>
                              <li><a class="dropdown-item" href="#">Another action</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                          </li>
                        </ul>

                        {% if request.user.is_authenticated %}
                          <a href="{% url 'home:profile_view' request.user.id %}">{{ request.user }}</a> | <a href="{% url 'home:logout' %}">Logout</a>
                        {% else %}
                          <a href="{% url 'home:login' %}">LogIn</a>
                        {% endif %}


                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
                <!-- END NAV BAR -->
            </div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% block content %}
                  
                {% endblock content %}
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col">
                <footer class="text-center text-white" style="background-color: #f1f1f1;">
                    <!-- Grid container -->
                    <div class="container pt-4">
                      <!-- Section: Social media -->
                      <section class="mb-4">
                        <!-- Facebook -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-facebook-f"></i
                        ></a>
                  
                        <!-- Twitter -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-twitter"></i
                        ></a>

                        <i class="glyphicon glyphicon-cloud"></i>

                  
                        <!-- Google -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-google"></i
                        ></a>
                  
                        <!-- Instagram -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-instagram"></i
                        ></a>
                  
                        <!-- Linkedin -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-linkedin"></i
                        ></a>
                        <!-- Github -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-github"></i
                        ></a>
                      </section>
                      <!-- Section: Social media -->
                    </div>
                    <!-- Grid container -->
                  
                    <!-- Copyright -->
                    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                      © 2020 Copyright:
                      <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
                    </div>
                    <!-- Copyright -->
                  </footer>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>