api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    path('v2/list/grantgoal/', views.GrantGoalListAPIView.as_view(), name="api_list_grantgoal"),
    path('v2/detail/grantgoal/<int:pk>/', views.GrantGoalDetailAPIView.as_view(), name="api_detail_grantgoal"),
    path('v2/create/grantgoal/', views.GrantGoalCreateAPIView.as_view(), name="api_create_grantgoal"),

    ### URL'S CLIENT ####

    path('client/list/grantgoal/', views.ListGrantGoalClient.as_view(), name="client_list"),
    path('client/create/grantgoal/', views.CreateGrantGoalClient.as_view(), name="api_create_client")
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    ### GRANTGOAL URLS ###
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_grantgoal"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_grantgoal"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_grantgoal"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_grantgoal"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name='create_grantgoal'),
]

dplaest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
]

api/models.py
from django.db import models

# Create your models here.

api/forms.py
from django import forms

from core.models import GrantGoal


class CreateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "user",
            "grantgoal_name",
            "description",
            "days_duration",
            "state",
            "status",
            "slug"
        ]
        widgets = {
            "user": forms.Select(attrs={"class": "form-select", "type":"select"}),
            "grantgoal_name": forms.TextInput(attrs={"type": "text", "class":"form-control", "placeholder":"Escribe el nombre del grantgoal"}),
            "description": forms.Textarea(attrs={"type": "text", "class":"form-control", "placeholder":"Escribe la descripcion del grantgoal", "rows":3}),
            "days_duration": forms.NumberInput(attrs={"type": "number", "class":"form-control", "placeholder":"Escribe el numero de dias de duracion del grantgoal"}),
            "state": forms.Select(attrs={"type": "select", "class": "form-select"})
        }

api/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.views import generic
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response

from core.models import GrantGoal
from .forms import CreateGrantGoalForm
from .serializers import GrantGoalSerializer, GrantGoalSerializerCreate


class GrantGoalListAPIView(generics.ListAPIView):
    queryset = GrantGoal.objects.filter(status=True)
    serializer_class = GrantGoalSerializer



    
class GrantGoalDetailAPIView(APIView):
   def get(self, request, pk, *args, **kwargs):
       queryset = GrantGoal.objects.get(pk=pk)
       data = GrantGoalSerializer(queryset).data
       return Response(data)
   


class GrantGoalCreateAPIView(generics.CreateAPIView):
    serializer_class = GrantGoalSerializerCreate



   ##### CLIENTS ######
import requests

class ListGrantGoalClient(generic.View):
    template_name = "api/list_client.html"
    context = {}
    url_api = "http://localhost:8000/api/v2/list/grantgoal/"

    def get(self, request):
        response = requests.get(url=self.url_api)
        self.context = {
            "grantgoals": response.json()
        }
        return render(request, self.template_name, self.context)


class CreateGrantGoalClient(generic.View):
    template_name = "api/create_client.html"
    context = {}
    url_api = "http://localhost:8000/api/v2/create/grantgoal/"
    form_class = CreateGrantGoalForm
    response = None
    payload = {}

    def get(self, request):
        self.context = {
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)
    

    def post(self, request, *args, **kwargs):
        self.payload = {            
            "grantgoal_name": request.POST["grantgoal_name"],
            "description": request.POST["description"],
            "days_duration": request.POST["days_duration"],
            "status": request.POST["status"],
            "state": request.POST["state"],
            "slug": request.POST["slug"],
            "user": request.POST["user"]
        }
        print("-------", self.payload)
        self.response = requests.post(url=self.url_api, data=self.payload)
        self.context = {
            "form": self.form_class
        }
        return redirect("api:client_list")

templates/api/create_client.html
{% extends "base/base.html" %}

{% block title %}
  CREATE GRANT GOAL VIEW CLIENT
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">Create</button>
            <a href="{% url 'core:list_grantgoal' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/api/list_client.html
{% extends "base/base.html" %}

{% block title %}
  LIST GRANT GOAL VIEW
{% endblock title %}

{% block content %}
    <table class="table">
        <thead>
            <th>ID</th>
            <th>GG NAME</th>
            <th>TIMESTAMP</th>
            <th>FINAL DATE</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in grantgoals %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.grantgoal_name }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td>{{ gg.final_date }}</td>
                    <td>{{ gg.status }}</td>
                    <td><a href="" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}